version: '3.9'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/vide.me-location.conf:/etc/nginx/vide.me-location.conf"
            - "./etc/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            #- php:/var/www/html
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
    php:
        image: nanoninja/php-fpm:8.1
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
            #- php:/pas
        #build:
        #   context: ./dirPHP
        #   dockerfile: Dockerfile
    composer:
        image: "composer"
        volumes:
            - "./web:/app"
        command: install --ignore-platform-reqs
#volumes:
#  php:
    # swarm
    deploy:
        placement:
        constraints:
          - "node.labels.TAG==prod"
